### ISSUE TITLE
Can not access the downloaded demand assets on Samsung Devices with Google Mobile Ads.

### ISSUE THREAD

**Issue by LazyBonesLZ** [googlecodelabs/android-dynamic-features#18]
After upload the AAB to the Internal-app-sharing in Google Play console, there is an issue that is if implement Google Mobile Ads SDK on Samsung devices, can not access the downloaded demand assets. 

Reproduce steps:
1. Build an AAB file and upload to GP Console Internal app sharing.
2. Copy download link to the device's browser and install.
3. Open the app and clikc the button 'Show Assets'.

Error Log:

> `java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
>      Caused by: java.io.FileNotFoundException: assets.txt
>         at android.content.res.AssetManager.nativeOpenAsset(Native Method)
>         at android.content.res.AssetManager.open(AssetManager.java:796)
>         at android.content.res.AssetManager.open(AssetManager.java:773)
>         at com.google.android.samples.dynamicfeatures.MainActivity.l(Unknown Source:20)
>         at com.google.android.samples.dynamicfeatures.MainActivity.a(Unknown Source:54)
>         at com.google.android.samples.dynamicfeatures.MainActivity.b(Unknown Source:43)
>         at com.google.android.samples.dynamicfeatures.MainActivity.a(Unknown Source:0)
>         at com.google.android.samples.dynamicfeatures.MainActivity$a$a.onClick(Unknown Source:67)
>         at android.view.View.performClick(View.java:7339)
>         at android.widget.TextView.performClick(TextView.java:14222)
>         at android.view.View.performClickInternal(View.java:7305)
>         at android.view.View.access$3200(View.java:846)
>         at android.view.View$PerformClick.run(View.java:27788)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7072)
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) `

Devices Info:
1.Samsung Tablet: SM-T810, Android 7.0
2.Samsung Tablet: SM-T510, Android 9.0
3.Samsung Phone: SM-G9730 Android 9.0

Demo:
[https://github.com/LazyBonesLZ/GPDynamicDeliveryIssue.git](https://github.com/LazyBonesLZ/GPDynamicDeliveryIssue.git)

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the codelab.

If you think that this is a problem with App bundles and dynamic delivery, please open a bug on the public issue tracker: https://buganizer.corp.google.com/issues/new?component=398856&template=1084213

Please reopen if you still think this is an issue with the codelab.
