### ISSUE TITLE
Can we do on/off Dynamic delivery based on Api level

### ISSUE THREAD

**Issue by g5-amit** [googlecodelabs/android-dynamic-features#25]
Can we implement the attribute ( dist:onDemand) like:
<dist:module
        dist:onDemand="@bool/isLessThanApi24"
        dist:title="@string/module_mapqr">
        <dist:fusing dist:include="true" />
    </dist:module>

Where boolean will decide for which Api level we want Dynamic Delivery.

I am asking this question since Dynamic delivery does not perform as stable delivery for Marshmallow and Below and we face crashes for it many times on Firebase

Once i do handle it using boolean variables like mentioned above , I always get the error:

Attribute 'onDemand' expected to have type 'boolean' but found:
 namespace_uri: "http://schemas.android.com/apk/distribution"
name: "onDemand"
value: "@bool/isLessThanApi24"
source {
  line_number: 15
}
compiled_item {
  ref {
    id: 2114060289
    name: "bool/isLessThanApi24"
  }
}

**Comment by ivincetti** [comment]
Yes, you can

Docs - [Configure conditional delivery](https://developer.android.com/guide/app-bundle/conditional-delivery)
```
<dist:module
        dist:title="@string/module_mapqr">
        <dist:delivery>
            <dist:on-demand />
            <dist:install-time>
                <dist:conditions>
                    <dist:min-sdk dist:value="21" />
                    <dist:max-sdk dist:value="24" />
                </dist:conditions>
            </dist:install-time>
        </dist:delivery>
        <dist:fusing dist:include="true" />
</dist:module>
```

**Comment by g5-amit** [comment]
Thank you.
