### ISSUE TITLE
Step 8 SplitInstallManager listener not working

### ISSUE THREAD

**Issue by ericntd** [googlecodelabs/android-dynamic-features#26]
There's a warning log
```
2020-08-04 15:39:14.919 12059-14497/? W/Finsky: [5091] zlg.a(43): Split install requested but the app is not owned, package: app.ericn.android.samples.dynamicfeatures.ondemand

```
I'm at the end of [step 8](https://codelabs.developers.google.com/codelabs/on-demand-dynamic-delivery/index.html#7), nothing is happening, no error, no exception, no downloading animation, it's just stuck as the below screenshot:
![Screenshot_20200804-154036_On Demand Sample](https://user-images.githubusercontent.com/19919208/89337490-014daf80-d669-11ea-814e-a76ac7b1cbcf.jpg)

I installed the app using `bundletool` command, straight into the device instead of the Google Play
(which is [either delayed or not working](https://stackoverflow.com/questions/63253254/google-play-blank-screen-loading-forever-internal-testing-and-public-alpha-track) as expected)
Could that have caused the issue?

Here are my `.apks` and `.aab` files
https://drive.google.com/file/d/1LXw4Ava76IWV2TTU0QZHeGsltiuiMZWq/view?usp=sharing

**Comment by pfmaggi** [comment]
As explained in the codelab, the app needs to be installed from Play (using internal app sharing is OK) to be able to download the on-demand modules as described.

There is now an alternative way to do this, but the codelab has not been updated to handle it. You can find more information in [this blog post](https://medium.com/androiddevelopers/local-development-and-testing-with-fakesplitinstallmanager-57083e1840a4)
